--------------------------------------------------------
--  DDL for Table ANIMALS
--------------------------------------------------------

  CREATE TABLE "AUSEMON"."ANIMALS" 
   (	"ID" NUMBER(12,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"COMMON_NAME" VARCHAR2(255 BYTE), 
	"SCIENTIFIC_NAME" VARCHAR2(255 BYTE), 
	"GUID" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5300514897588604" ;
--------------------------------------------------------
--  DDL for Index ANIMALS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUSEMON"."ANIMALS_PK" ON "AUSEMON"."ANIMALS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5300514897588604" ;
--------------------------------------------------------
--  Constraints for Table ANIMALS
--------------------------------------------------------

  ALTER TABLE "AUSEMON"."ANIMALS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AUSEMON"."ANIMALS" MODIFY ("COMMON_NAME" NOT NULL ENABLE);
  ALTER TABLE "AUSEMON"."ANIMALS" ADD CONSTRAINT "ANIMALS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5300514897588604"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_ANIMALS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AUSEMON"."BI_ANIMALS" 
  before insert on "ANIMALS"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "ANIMALS_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end;
/
ALTER TRIGGER "AUSEMON"."BI_ANIMALS" ENABLE;
