--------------------------------------------------------
--  DDL for Table GEO_TEMP
--------------------------------------------------------

  CREATE TABLE "AUSEMON"."GEO_TEMP" 
   (	"OCCURRENCE_NUMBER" NUMBER, 
	"LOCATION" "SDO_GEOMETRY"
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5300514897588604" 
 VARRAY "LOCATION"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
  ( TABLESPACE "APEX_5300514897588604" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 VARRAY "LOCATION"."SDO_ORDINATES" STORE AS SECUREFILE LOB 
  ( TABLESPACE "APEX_5300514897588604" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index GEO_TMP_IDX5
--------------------------------------------------------

  CREATE INDEX "AUSEMON"."GEO_TMP_IDX5" ON "AUSEMON"."GEO_TEMP" ("LOCATION") 
   INDEXTYPE IS "MDSYS"."SPATIAL_INDEX" ;
