--------------------------------------------------------
--  DDL for Table OCCURRENCES
--------------------------------------------------------

  CREATE TABLE "AUSEMON"."OCCURRENCES" 
   (	"OCCURRENCE_NUMBER" NUMBER, 
	"SCIENTIFIC_NAME" VARCHAR2(200 BYTE), 
	"COMMON_NAME" VARCHAR2(200 BYTE), 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"LOCATION" "SDO_GEOMETRY"
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5300514897588604" 
 VARRAY "LOCATION"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
  ( TABLESPACE "APEX_5300514897588604" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 VARRAY "LOCATION"."SDO_ORDINATES" STORE AS SECUREFILE LOB 
  ( TABLESPACE "APEX_5300514897588604" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index OCCURRENCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUSEMON"."OCCURRENCES_PK" ON "AUSEMON"."OCCURRENCES" ("OCCURRENCE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5300514897588604" ;
--------------------------------------------------------
--  Constraints for Table OCCURRENCES
--------------------------------------------------------

  ALTER TABLE "AUSEMON"."OCCURRENCES" MODIFY ("OCCURRENCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "AUSEMON"."OCCURRENCES" MODIFY ("SCIENTIFIC_NAME" NOT NULL ENABLE);
  ALTER TABLE "AUSEMON"."OCCURRENCES" MODIFY ("LATITUDE" NOT NULL ENABLE);
  ALTER TABLE "AUSEMON"."OCCURRENCES" MODIFY ("LONGITUDE" NOT NULL ENABLE);
  ALTER TABLE "AUSEMON"."OCCURRENCES" ADD CONSTRAINT "OCCURRENCES_PK" PRIMARY KEY ("OCCURRENCE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_5300514897588604"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_OCCURRENCES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AUSEMON"."BI_OCCURRENCES" 
  before insert on "OCCURRENCES"               
  for each row  
begin   
  if :NEW."OCCURRENCE_NUMBER" is null then 
    select "OCCURRENCES_SEQ".nextval into :NEW."OCCURRENCE_NUMBER" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER "AUSEMON"."BI_OCCURRENCES" ENABLE;
